### PR TITLE
Add support for SVG format

### PR DESCRIPTION
**Pull request by Jack-42**
This change adds support to displaying/saving molecules using SVG format. I've also made SVG the default format, but can revert back to PNG being the default if desired.

### CODE REVIEW

**Review by Priyansh-Kedia — COMMENTED** [review]
Hello @Jack-42 
The code looks good, thanks for the changes

However, I think it is better to keep the default image option to be PNG or JPEG. I say this because usually when the results are to be analysed and downloaded, viewing SVG image is supported on browsers, but not on image viewers on the system. 
In order to analyze the results (images), one would ideally want to view the image in their image viewer software and not on the browser

If you agree with the same, please make the change

**Comment by Priyansh-Kedia** [comment]
Also, if I select any other image size than m (180x260), the results are generated as expected, but the size option resets to the default, which is m currently. 

Ideally if I select xl option, the results should also be presented with 'xl' selected.

**Comment by Jack-42** [comment]
@Priyansh-Kedia thanks for your feedback. I agree that since image viewers may not support SVG it makes sense to use PNG as the default. I've changed the default back to PNG. 

As well, I've made it so that the user option for image size (and also image format) persists after the user generates results. I will note that I don't have a great amount of experience with html/javascript, so if something seems off please let me know (I admittedly used chatgpt to generate some boilerplate for the script part).

**Review by Priyansh-Kedia — APPROVED** [review]

**Comment by Priyansh-Kedia** [comment]
Hello @Jack-42 
The code seems fine. There can be other ways to handle this (like using ids in JS and searching using id rather than class), but this should work fine for our case as there is not much of processing happening here. 

Thanks for making the changes. I have approved the changes and the PR can now be merged.

**Pull request merged**
