### PR TITLE
Fix issue of styles.css not loading in production

### PR DESCRIPTION
**Pull request by Jack-42**
Fixes issue: #13

### CODE REVIEW

**Comment by Priyansh-Kedia** [comment]
Hi @Jack-42
I am still testing this change. From what I think, just changing the link in HTML code for the static file should be enough, as we are already mapping the static directory, and do not need to map the content of the directory again.

**Comment by Jack-42** [comment]
Hey @Priyansh-Kedia 

Thanks for looking at this. I agree that changing the link for the static file should be enough in theory. However, in practice I was finding that the .css file was not being copied into the docker container without the changes to docker-compose-prod.yml. This is indeed strange behavior, as the "COPY . ." command in Dockerfile.prod should copy everything over.

**Comment by Priyansh-Kedia** [comment]
Hello @Jack-42 
I have made a small change in docker compose prod file. Running containers using this files also copies the `styles.css` in the directory structure. Please check and confirm.

If the CSS still does not work in our case, this problem can be outside docker. Please let me know if the CSS works with the changes I made.

Thanks

**Comment by Jack-42** [comment]
I think there is an issue with the new changes. Without the changes the demo looks like this:
image

However, with the changes the images do not display:
image

I confirmed that the CSS file is in the docker container with the changes (which makes sense given that the borders and other styles are still present). However, I believe commenting out "static_vol:/cfchemapps/static" has made it so that the images can't be found/loaded properly.

**Comment by Priyansh-Kedia** [comment]
Hi @Jack-42 
As I had previously mentioned, that the problem might not be with the docker container, which seems to be the case.

It looks like even though we have a persistent volume attached with docker, the static files were not served. To achieve this, I added whitenoise (package to handle static file serving by automatic file resolution etc.) for the file serving, and only maintained a single static volume between the host machine and the container. 

Attached is the screenshot of the working app with the code of the last commit
Screenshot 2024-01-04 at 5 39 19 PM

Please let me know if this works for you as expected

Also, can you make sure to add `DEBUB=1` in the `.env.prod` file on the EC2 server

Thanks

**Comment by Jack-42** [comment]
Hey @Priyansh-Kedia 

I tested the code on the EC2 server and the CSS styling is missing (see screenshots below):
image
image

I did update `DEBUG=1` in `.env.prod` on the EC2 server by the way. I realize this isn't a high-risk application, but should we have any security concerns running with `DEBUG=1`? For now I reset the EC2 server back to the master branch with the fix mentioned in issue #13 and `DEBUG=0.`

**Comment by Priyansh-Kedia** [comment]
Hello @Jack-42 
On further investigation, I discovered that the issue persists only in case of the server running on EC2 instance. When the same production code is run in an environment other than AWS EC2, it runs as expected. 

I am currently searching for reasons for the same, and shall let you know as soon as I have something

Thank you

**Comment by Priyansh-Kedia** [comment]
Hello @Jack-42 
There was a small issue with the volumes and the path that had been defined to mount them. I have fixed the issue now and also checked with the EC2 server. All the static files are now being copied.

The server is currently running on this current branch code. Please check the same on your end. 

If everything seems fine, we can merge the branch after cleaning out the unnecessary and commented code.

Thanks

**Comment by Jack-42** [comment]
@Priyansh-Kedia Thanks for looking at this! The fix seems to have worked, the website is working as expected. Just to double-check again, we'll be ok with `DEBUG=1` being set for our production server? For example, right now if I cause an error (for example using Issue #12 ) then rather than a generic error code I get a detailed error page including information such as the following:
image

Once we confirm the `DEBUG` status is ok I can go ahead and clean out the comments/unnecessary code

**Comment by Priyansh-Kedia** [comment]
> @Priyansh-Kedia Thanks for looking at this! The fix seems to have worked, the website is working as expected. Just to double-check again, we'll be ok with `DEBUG=1` being set for our production server? For example, right now if I cause an error (for example using Issue #12 ) then rather than a generic error code I get a detailed error page including information such as the following:
> 
> image
> 
> 
> 
> Once we confirm the `DEBUG` status is ok I can go ahead and clean out the comments/unnecessary code
> 
> 

Hello @Jack-42 
Thanks for confirming. We will run the production server again on the master branch using DEBUG=1 after we merge this fix. 

Ideally production servers should be run using master branch, currently I deployed it for testing purpose. 

Thanks

**Comment by Jack-42** [comment]
> > @Priyansh-Kedia Thanks for looking at this! The fix seems to have worked, the website is working as expected. Just to double-check again, we'll be ok with `DEBUG=1` being set for our production server? For example, right now if I cause an error (for example using Issue #12 ) then rather than a generic error code I get a detailed error page including information such as the following:
> > image
> > Once we confirm the `DEBUG` status is ok I can go ahead and clean out the comments/unnecessary code
> 
> Hello @Jack-42 Thanks for confirming. We will run the production server again on the master branch using DEBUG=1 after we merge this fix.
> 
> Ideally production servers should be run using master branch, currently I deployed it for testing purpose.
> 
> Thanks

Thanks for confirming. I've gone ahead and removed the commented-out/unnecessary code related to this pull request. If everything looks good to you it should be ready to merge.

**Comment by Priyansh-Kedia** [comment]
Hello @Jack-42 
The code looks good now. We can now merge the fix into the `master` branch

Can you also stop and restart the server on EC2 using the `master` branch, using `DEBUG=0` in `.env.prod`. 

Thanks

**Pull request merged**
